# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cde82fd836be3c9de338917e10a07cf525ed9fe7876c62cfeff2050a94d9ed4387e7986f84cef6c2205e59b471b8bff9f2839345d82c7eb89de7cd428d4a3611

test:
  secret_key_base: 4eb4efea4ca4250a3b8401fec273bc7ba4b14c726604f0542d615949c56b85cf9ad2ff68a33adea2eaafd29c99097e5d65448219b5700e1aedbe4993c5192c81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
